"""Detector catalog entries."""

from __future__ import annotations

from .catalog_models import DetectorMeta

DETECTORS: dict[str, DetectorMeta] = {
    # ── Auto-fixable ──────────────────────────────────────
    "unused": DetectorMeta(
        "unused",
        "unused",
        "Code quality",
        "auto_fix",
        "remove unused imports and variables",
        fixers=("unused-imports", "unused-vars", "unused-params"),
        tier=3,
        subjective_dimensions=("design_coherence",),
    ),
    "logs": DetectorMeta(
        "logs",
        "logs",
        "Code quality",
        "auto_fix",
        "remove debug logs",
        fixers=("debug-logs",),
        tier=3,
        subjective_dimensions=("logic_clarity",),
    ),
    "exports": DetectorMeta(
        "exports",
        "exports",
        "Code quality",
        "manual_fix",
        "run `knip --fix` to remove dead exports",
        tier=3,
        subjective_dimensions=("api_surface_coherence",),
    ),
    "smells": DetectorMeta(
        "smells",
        "smells",
        "Code quality",
        "auto_fix",
        "fix code smells — dead useEffect, empty if chains",
        fixers=("dead-useeffect", "empty-if-chain"),
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("design_coherence", "error_consistency", "logic_clarity"),
    ),
    # ── Reorganize (move tool) ────────────────────────────
    "orphaned": DetectorMeta(
        "orphaned",
        "orphaned",
        "Code quality",
        "reorganize",
        "delete dead files or relocate with `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("design_coherence",),
    ),
    "uncalled_functions": DetectorMeta(
        "uncalled_functions",
        "uncalled functions",
        "Code quality",
        "refactor",
        "remove dead functions or document why they're retained",
        needs_judgment=True,
        marks_dims_stale=True,
        subjective_dimensions=("design_coherence",),
    ),
    "unused_enums": DetectorMeta(
        "unused_enums",
        "unused enums",
        "unused",
        "manual_fix",
        "remove unused enum classes or add imports where they belong",
        subjective_dimensions=("design_coherence",),
    ),
    "flat_dirs": DetectorMeta(
        "flat_dirs",
        "flat dirs",
        "Code quality",
        "reorganize",
        "create subdirectories and use `desloppify move`",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("package_organization",),
    ),
    "naming": DetectorMeta(
        "naming",
        "naming",
        "Code quality",
        "reorganize",
        "rename files with `desloppify move` to fix conventions",
        tool="move",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("convention_outlier", "naming_quality"),
    ),
    "single_use": DetectorMeta(
        "single_use",
        "single_use",
        "Code quality",
        "reorganize",
        "inline or relocate with `desloppify move`",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        subjective_dimensions=("abstraction_fitness",),
    ),
    "coupling": DetectorMeta(
        "coupling",
        "coupling",
        "Code quality",
        "reorganize",
        "fix boundary violations with `desloppify move`",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("cross_module_architecture",),
    ),
    "cycles": DetectorMeta(
        "cycles",
        "cycles",
        "Security",
        "reorganize",
        "break cycles by extracting shared code or using `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=4,
        marks_dims_stale=True,
        subjective_dimensions=("cross_module_architecture", "dependency_health"),
    ),
    "facade": DetectorMeta(
        "facade",
        "facade",
        "Code quality",
        "reorganize",
        "flatten re-export facades or consolidate barrel files",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        subjective_dimensions=("abstraction_fitness",),
    ),
    # ── Refactor ──────────────────────────────────────────
    "structural": DetectorMeta(
        "structural",
        "structural",
        "File health",
        "refactor",
        "review large files — split only when responsibilities are clearly separable",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("design_coherence", "abstraction_fitness", "logic_clarity"),
    ),
    "props": DetectorMeta(
        "props",
        "props",
        "Code quality",
        "refactor",
        "split bloated components/widgets, extract sub-components/sub-widgets",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        subjective_dimensions=("abstraction_fitness",),
    ),
    "react": DetectorMeta(
        "react",
        "react",
        "Code quality",
        "refactor",
        "refactor React antipatterns (state sync, provider nesting, hook bloat)",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        subjective_dimensions=("design_coherence",),
    ),
    "dupes": DetectorMeta(
        "dupes",
        "dupes",
        "Duplication",
        "refactor",
        "extract shared utility or consolidate duplicates",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("convention_outlier",),
    ),
    "patterns": DetectorMeta(
        "patterns",
        "patterns",
        "Code quality",
        "refactor",
        "align to single pattern across the codebase",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        subjective_dimensions=("convention_outlier",),
    ),
    "dict_keys": DetectorMeta(
        "dict_keys",
        "dict keys",
        "Code quality",
        "refactor",
        "fix dict key mismatches — dead writes are likely dead code, "
        "schema drift suggests a typo or missed rename",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        subjective_dimensions=("type_safety",),
    ),
    "test_coverage": DetectorMeta(
        "test_coverage",
        "test coverage",
        "Test health",
        "refactor",
        "add tests for untested production modules — prioritize by import count",
        tier=4,
        subjective_dimensions=("test_strategy",),
    ),
    "signature": DetectorMeta(
        "signature",
        "signature",
        "Code quality",
        "refactor",
        "consolidate inconsistent function signatures",
        needs_judgment=True,
        standalone_threshold="high",
        subjective_dimensions=("convention_outlier",),
    ),
    "global_mutable_config": DetectorMeta(
        "global_mutable_config",
        "global mutable config",
        "Code quality",
        "manual_fix",
        "refactor module-level mutable state — use explicit init functions or dependency injection",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("initialization_coupling",),
    ),
    "private_imports": DetectorMeta(
        "private_imports",
        "private imports",
        "Code quality",
        "manual_fix",
        "stop importing private symbols across module boundaries",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("cross_module_architecture",),
    ),
    "layer_violation": DetectorMeta(
        "layer_violation",
        "layer violation",
        "Code quality",
        "manual_fix",
        "fix architectural layer violations — move shared code to the correct layer",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("cross_module_architecture",),
    ),
    "responsibility_cohesion": DetectorMeta(
        "responsibility_cohesion",
        "responsibility cohesion",
        "Code quality",
        "refactor",
        "split modules with too many responsibilities — extract focused sub-modules",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("design_coherence", "abstraction_fitness"),
    ),
    "boilerplate_duplication": DetectorMeta(
        "boilerplate_duplication",
        "boilerplate duplication",
        "Duplication",
        "refactor",
        "extract shared boilerplate into reusable helpers or base classes",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
        subjective_dimensions=("convention_outlier",),
    ),
    "stale_wontfix": DetectorMeta(
        "stale_wontfix",
        "stale wontfix",
        "Code quality",
        "manual_fix",
        "re-evaluate old wontfix decisions — fix, document, or escalate",
    ),
    "concerns": DetectorMeta(
        "concerns",
        "design concerns",
        "Design coherence",
        "refactor",
        "address design concerns confirmed by subjective evaluation",
    ),
    # ── Manual fix ────────────────────────────────────────
    "deprecated": DetectorMeta(
        "deprecated",
        "deprecated",
        "Code quality",
        "manual_fix",
        "remove deprecated symbols or migrate callers",
        tier=3,
        subjective_dimensions=("incomplete_migration",),
    ),
    "stale_exclude": DetectorMeta(
        "stale_exclude",
        "stale exclude",
        "Code quality",
        "manual_fix",
        "remove stale exclusion or verify it's still needed",
        tier=3,
    ),
    "security": DetectorMeta(
        "security",
        "security",
        "Security",
        "manual_fix",
        "review and fix security issues — prioritize by severity",
        tier=4,
        subjective_dimensions=("error_consistency",),
    ),
    # ── Subjective review ────────────────────────────────────
    "review": DetectorMeta(
        "review",
        "design review",
        "Test health",
        "refactor",
        "address design quality issues from AI code review",
    ),
    "subjective_review": DetectorMeta(
        "subjective_review",
        "subjective review",
        "Test health",
        "manual_fix",
        "run `desloppify review --prepare` to evaluate files against quality dimensions",
        tier=4,
    ),
}


__all__ = ["DETECTORS"]
