"""Stable public export list for ``desloppify.engine.plan`` facade."""

from __future__ import annotations

PLAN_PUBLIC_EXPORTS = [
    # schema
    "EPIC_PREFIX",
    "ExecutionLogEntry",
    "PLAN_VERSION",
    "Cluster",
    "CommitRecord",
    "ItemOverride",
    "PlanModel",
    "SkipEntry",
    "SupersededEntry",
    "VALID_EPIC_DIRECTIONS",
    "VALID_SKIP_KINDS",
    "USER_SKIP_KINDS",
    "empty_plan",
    "ensure_plan_defaults",
    "triage_clusters",
    "validate_plan",
    # persistence
    "PLAN_FILE",
    "get_plan_file",
    "has_living_plan",
    "load_plan",
    "plan_lock",
    "plan_path_for_state",
    "save_plan",
    # operations
    "add_to_cluster",
    "annotate_issue",
    "append_log_entry",
    "clear_focus",
    "create_cluster",
    "delete_cluster",
    "describe_issue",
    "merge_clusters",
    "move_cluster",
    "move_items",
    "purge_ids",
    "remove_from_cluster",
    "reset_plan",
    "resurface_stale_skips",
    "set_focus",
    "skip_items",
    "skip_kind_from_flags",
    "skip_kind_requires_attestation",
    "skip_kind_requires_note",
    "skip_kind_state_status",
    "SKIP_KIND_LABELS",
    "unskip_items",
    "annotation_counts",
    "auto_complete_steps",
    "format_steps",
    "normalize_step",
    "parse_steps_file",
    "step_summary",
    # reconcile
    "ReconcileResult",
    "ReviewImportSyncResult",
    "reconcile_plan_after_scan",
    "sync_plan_after_review_import",
    # commit tracking
    "add_uncommitted_issues",
    "commit_tracking_summary",
    "filter_issue_ids_by_pattern",
    "find_commit_for_issue",
    "generate_pr_body",
    "get_uncommitted_issues",
    "purge_uncommitted_ids",
    "record_commit",
    "suggest_commit_message",
    # auto-clustering
    "AUTO_PREFIX",
    "auto_cluster_issues",
    # constants + sync
    "TRIAGE_IDS",
    "TRIAGE_PREFIX",
    "TRIAGE_STAGE_IDS",
    "SYNTHETIC_PREFIXES",
    "WORKFLOW_CREATE_PLAN_ID",
    "WORKFLOW_SCORE_CHECKPOINT_ID",
    "WORKFLOW_PREFIX",
    "QueueSyncResult",
    "compute_new_issue_ids",
    "current_unscored_ids",
    "is_triage_stale",
    "sync_communicate_score_needed",
    "sync_create_plan_needed",
    "sync_import_scores_needed",
    "sync_score_checkpoint_needed",
    "sync_stale_dimensions",
    "sync_triage_needed",
    "sync_unscored_dimensions",
    "open_review_ids",
    "review_issue_snapshot_hash",
    "_REVIEW_DETECTORS",
    # epic triage
    "TriageInput",
    "build_triage_prompt",
    "collect_triage_input",
    "detect_recurring_patterns",
    "extract_issue_citations",
    "TRIAGE_STAGE_DEPENDENCIES",
    "TRIAGE_STAGE_LABELS",
    "TRIAGE_CMD_OBSERVE",
    "TRIAGE_CMD_REFLECT",
    "TRIAGE_CMD_ORGANIZE",
    "TRIAGE_CMD_ENRICH",
    "TRIAGE_CMD_SENSE_CHECK",
    "TRIAGE_CMD_COMPLETE",
    "TRIAGE_CMD_COMPLETE_VERBOSE",
    "TRIAGE_CMD_CONFIRM_EXISTING",
    "TRIAGE_CMD_CLUSTER_CREATE",
    "TRIAGE_CMD_CLUSTER_ADD",
    "TRIAGE_CMD_CLUSTER_ENRICH",
    "TRIAGE_CMD_CLUSTER_ENRICH_COMPACT",
    "TRIAGE_CMD_CLUSTER_STEPS",
    # subjective policy
    "compute_subjective_visibility",
    # triage
    "triage_phase_banner",
]


__all__ = ["PLAN_PUBLIC_EXPORTS"]
