"""Detector catalog entries."""

from __future__ import annotations

from desloppify.base.registry_catalog_models import DetectorMeta

DETECTORS: dict[str, DetectorMeta] = {
    # ── Auto-fixable ──────────────────────────────────────
    "unused": DetectorMeta(
        "unused",
        "unused",
        "Code quality",
        "auto_fix",
        "remove unused imports and variables",
        fixers=("unused-imports", "unused-vars", "unused-params"),
        tier=3,
    ),
    "logs": DetectorMeta(
        "logs",
        "logs",
        "Code quality",
        "auto_fix",
        "remove debug logs",
        fixers=("debug-logs",),
        tier=3,
    ),
    "exports": DetectorMeta(
        "exports",
        "exports",
        "Code quality",
        "manual_fix",
        "run `knip --fix` to remove dead exports",
        tier=3,
    ),
    "smells": DetectorMeta(
        "smells",
        "smells",
        "Code quality",
        "auto_fix",
        "fix code smells — dead useEffect, empty if chains",
        fixers=("dead-useeffect", "empty-if-chain"),
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
    ),
    # ── Reorganize (move tool) ────────────────────────────
    "orphaned": DetectorMeta(
        "orphaned",
        "orphaned",
        "Code quality",
        "reorganize",
        "delete dead files or relocate with `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=3,
        marks_dims_stale=True,
    ),
    "uncalled_functions": DetectorMeta(
        "uncalled_functions",
        "uncalled functions",
        "Code quality",
        "refactor",
        "remove dead functions or document why they're retained",
        needs_judgment=True,
        marks_dims_stale=True,
    ),
    "unused_enums": DetectorMeta(
        "unused_enums",
        "unused enums",
        "unused",
        "manual_fix",
        "remove unused enum classes or add imports where they belong",
    ),
    "flat_dirs": DetectorMeta(
        "flat_dirs",
        "flat dirs",
        "Code quality",
        "reorganize",
        "create subdirectories and use `desloppify move`",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "naming": DetectorMeta(
        "naming",
        "naming",
        "Code quality",
        "reorganize",
        "rename files with `desloppify move` to fix conventions",
        tool="move",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
    ),
    "single_use": DetectorMeta(
        "single_use",
        "single_use",
        "Code quality",
        "reorganize",
        "inline or relocate with `desloppify move`",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
    ),
    "coupling": DetectorMeta(
        "coupling",
        "coupling",
        "Code quality",
        "reorganize",
        "fix boundary violations with `desloppify move`",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "cycles": DetectorMeta(
        "cycles",
        "cycles",
        "Security",
        "reorganize",
        "break cycles by extracting shared code or using `desloppify move`",
        tool="move",
        needs_judgment=True,
        tier=4,
        marks_dims_stale=True,
    ),
    "facade": DetectorMeta(
        "facade",
        "facade",
        "Code quality",
        "reorganize",
        "flatten re-export facades or consolidate barrel files",
        tool="move",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
    ),
    # ── Refactor ──────────────────────────────────────────
    "structural": DetectorMeta(
        "structural",
        "structural",
        "File health",
        "refactor",
        "review large files — split only when responsibilities are clearly separable",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "props": DetectorMeta(
        "props",
        "props",
        "Code quality",
        "refactor",
        "split bloated components, extract sub-components",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "react": DetectorMeta(
        "react",
        "react",
        "Code quality",
        "refactor",
        "refactor React antipatterns (state sync, provider nesting, hook bloat)",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "dupes": DetectorMeta(
        "dupes",
        "dupes",
        "Duplication",
        "refactor",
        "extract shared utility or consolidate duplicates",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
        marks_dims_stale=True,
    ),
    "patterns": DetectorMeta(
        "patterns",
        "patterns",
        "Code quality",
        "refactor",
        "align to single pattern across the codebase",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "dict_keys": DetectorMeta(
        "dict_keys",
        "dict keys",
        "Code quality",
        "refactor",
        "fix dict key mismatches — dead writes are likely dead code, "
        "schema drift suggests a typo or missed rename",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "test_coverage": DetectorMeta(
        "test_coverage",
        "test coverage",
        "Test health",
        "refactor",
        "add tests for untested production modules — prioritize by import count",
        tier=4,
    ),
    "signature": DetectorMeta(
        "signature",
        "signature",
        "Code quality",
        "refactor",
        "consolidate inconsistent function signatures",
        needs_judgment=True,
        standalone_threshold="high",
    ),
    "clippy_warning": DetectorMeta(
        "clippy_warning",
        "clippy warning",
        "Code quality",
        "manual_fix",
        "fix Clippy diagnostics or justify narrow suppressions close to the code",
        tier=2,
    ),
    "cargo_error": DetectorMeta(
        "cargo_error",
        "cargo error",
        "Code quality",
        "manual_fix",
        "fix compiler errors and keep the crate buildable under `cargo check`",
        tier=2,
    ),
    "rustdoc_warning": DetectorMeta(
        "rustdoc_warning",
        "rustdoc warning",
        "Test health",
        "manual_fix",
        "fix rustdoc warnings and keep public docs and links valid",
        tier=2,
    ),
    "rust_import_hygiene": DetectorMeta(
        "rust_import_hygiene",
        "rust import hygiene",
        "Code quality",
        "auto_fix",
        "rewrite same-crate imports to `crate::...` paths for clearer internal boundaries",
        fixers=("crate-imports",),
        tier=2,
    ),
    "rust_feature_hygiene": DetectorMeta(
        "rust_feature_hygiene",
        "rust feature hygiene",
        "Code quality",
        "auto_fix",
        "declare referenced cfg features in Cargo.toml and keep feature flags additive",
        fixers=("cargo-features",),
        tier=2,
    ),
    "rust_doctest": DetectorMeta(
        "rust_doctest",
        "rust doctest",
        "Test health",
        "auto_fix",
        "wire README Rust examples into doctests so docs stay runnable",
        fixers=("readme-doctests",),
        tier=2,
    ),
    "rust_api_convention": DetectorMeta(
        "rust_api_convention",
        "rust API convention",
        "Code quality",
        "manual_fix",
        "align public naming and conversion conventions to the Rust API Guidelines",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "rust_error_boundary": DetectorMeta(
        "rust_error_boundary",
        "rust error boundary",
        "Code quality",
        "manual_fix",
        "use meaningful public error types and avoid panic-style behavior on public APIs",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=2,
    ),
    "rust_future_proofing": DetectorMeta(
        "rust_future_proofing",
        "rust future-proofing",
        "Code quality",
        "manual_fix",
        "review public structs and enums for brittle API shape and consider `#[non_exhaustive]` where appropriate",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "rust_thread_safety": DetectorMeta(
        "rust_thread_safety",
        "rust thread safety",
        "Test health",
        "manual_fix",
        "add Send/Sync assertion tests or document why a public type is intentionally not thread-safe",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "rust_async_locking": DetectorMeta(
        "rust_async_locking",
        "rust async locking",
        "Code quality",
        "manual_fix",
        "drop lock guards before awaiting and avoid blocking std::sync locks on async executor threads",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "rust_drop_safety": DetectorMeta(
        "rust_drop_safety",
        "rust drop safety",
        "Code quality",
        "manual_fix",
        "keep Drop implementations infallible — avoid panic, unwrap, and expect during destructor cleanup",
        needs_judgment=True,
        standalone_threshold="medium",
        tier=3,
    ),
    "rust_unsafe_api": DetectorMeta(
        "rust_unsafe_api",
        "rust unsafe API",
        "Code quality",
        "manual_fix",
        "replace unchecked Rust APIs with checked alternatives or document the required invariants locally",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
    ),
    "global_mutable_config": DetectorMeta(
        "global_mutable_config",
        "global mutable config",
        "Code quality",
        "manual_fix",
        "refactor module-level mutable state — use explicit init functions or dependency injection",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "private_imports": DetectorMeta(
        "private_imports",
        "private imports",
        "Code quality",
        "manual_fix",
        "stop importing private symbols across module boundaries",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "layer_violation": DetectorMeta(
        "layer_violation",
        "layer violation",
        "Code quality",
        "manual_fix",
        "fix architectural layer violations — move shared code to the correct layer",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "responsibility_cohesion": DetectorMeta(
        "responsibility_cohesion",
        "responsibility cohesion",
        "Code quality",
        "refactor",
        "split modules with too many responsibilities — extract focused sub-modules",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "boilerplate_duplication": DetectorMeta(
        "boilerplate_duplication",
        "boilerplate duplication",
        "Duplication",
        "refactor",
        "extract shared boilerplate into reusable helpers or base classes",
        needs_judgment=True,
        standalone_threshold="high",
        tier=3,
        marks_dims_stale=True,
    ),
    "stale_wontfix": DetectorMeta(
        "stale_wontfix",
        "stale wontfix",
        "Code quality",
        "manual_fix",
        "re-evaluate old wontfix decisions — fix, document, or escalate",
    ),
    "concerns": DetectorMeta(
        "concerns",
        "design concerns",
        "Design coherence",
        "refactor",
        "address design concerns confirmed by subjective evaluation",
    ),
    # ── Manual fix ────────────────────────────────────────
    "deprecated": DetectorMeta(
        "deprecated",
        "deprecated",
        "Code quality",
        "manual_fix",
        "remove deprecated symbols or migrate callers",
        tier=3,
    ),
    "stale_exclude": DetectorMeta(
        "stale_exclude",
        "stale exclude",
        "Code quality",
        "manual_fix",
        "remove stale exclusion or verify it's still needed",
        tier=3,
    ),
    "security": DetectorMeta(
        "security",
        "security",
        "Security",
        "manual_fix",
        "review and fix security issues — prioritize by severity",
        tier=4,
    ),
    # ── Subjective review ────────────────────────────────────
    "review": DetectorMeta(
        "review",
        "design review",
        "Test health",
        "refactor",
        "address design quality issues from AI code review",
    ),
    "subjective_review": DetectorMeta(
        "subjective_review",
        "subjective review",
        "Test health",
        "manual_fix",
        "run `desloppify review --prepare` to evaluate files against quality dimensions",
        tier=4,
    ),
}


__all__ = ["DETECTORS"]
