"""Focused public plan API for persisted plan state and contracts."""

from __future__ import annotations

from desloppify.engine._plan.commit_tracking import (
    add_uncommitted_issues,
    commit_tracking_summary,
    filter_issue_ids_by_pattern,
    find_commit_for_issue,
    generate_pr_body,
    get_uncommitted_issues,
    purge_uncommitted_ids,
    record_commit,
    suggest_commit_message,
)
from desloppify.engine._plan.persistence import (
    PLAN_FILE,
    PlanLoadStatus,
    get_plan_file,
    has_living_plan,
    load_plan,
    plan_lock,
    plan_path_for_state,
    resolve_plan_load_status,
    save_plan,
)
from desloppify.engine._plan.policy.project import (
    PolicyLoadResult,
    add_rule,
    load_policy,
    load_policy_result,
    remove_rule,
    render_policy_block,
    save_policy,
)
from desloppify.engine._plan.schema import (
    ActionStep,
    EpicTriageMeta,
    EPIC_PREFIX,
    PLAN_VERSION,
    VALID_EPIC_DIRECTIONS,
    VALID_SKIP_KINDS,
    Cluster,
    CommitRecord,
    ExecutionLogEntry,
    ItemOverride,
    PlanModel,
    SkipEntry,
    SupersededEntry,
    empty_plan,
    ensure_plan_defaults,
    triage_clusters,
    validate_plan,
)

__all__ = [
    "ActionStep",
    "Cluster",
    "CommitRecord",
    "EPIC_PREFIX",
    "EpicTriageMeta",
    "ExecutionLogEntry",
    "ItemOverride",
    "PLAN_FILE",
    "PLAN_VERSION",
    "PlanLoadStatus",
    "PolicyLoadResult",
    "PlanModel",
    "SkipEntry",
    "SupersededEntry",
    "VALID_EPIC_DIRECTIONS",
    "VALID_SKIP_KINDS",
    "add_rule",
    "add_uncommitted_issues",
    "commit_tracking_summary",
    "empty_plan",
    "ensure_plan_defaults",
    "filter_issue_ids_by_pattern",
    "find_commit_for_issue",
    "generate_pr_body",
    "get_plan_file",
    "get_uncommitted_issues",
    "has_living_plan",
    "load_plan",
    "load_policy",
    "load_policy_result",
    "plan_lock",
    "plan_path_for_state",
    "purge_uncommitted_ids",
    "record_commit",
    "remove_rule",
    "render_policy_block",
    "resolve_plan_load_status",
    "save_plan",
    "save_policy",
    "suggest_commit_message",
    "triage_clusters",
    "validate_plan",
]
